server:
  port: 20400
spring:
  application:
    name: rabb-gateway-alibaba
  cloud:
#    gateway:
#      routes:
#        - id: test-route
#          uri: http://lazyrabbit.xyz
#          predicates:
#            - Path=/rabb/**
#          filters:
#            - RewritePath=/rabb/?(?<segment>.*), /$\{segment}
#        - id: prefixpath_route
#          uri: lb://rabb-nacos-provider #此处需要使用lb协议
#          predicates:
#            - Path=/filter/**
#          filters:
#            - RewritePath=/filter/?(?<segment>.*), /$\{segment}
#      discovery:
#        locator:
#          enabled: true #开启从注册中心动态创建路由的功能
#          lower-case-service-id: true #使用小写服务名，默认是大写
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8880
#        port: 8719
#      filter:
#        enabled: false
      datasource:
        ds:
          nacos:
            server-addr: 127.0.0.1:8848
            data-id: rabb-gateway-sentinel-rule
            group-id: DEFAULT_GROUP
            username: nacos
            password: nacos
            ruleType: gw-flow