server:
  port: 11000
spring:
  application:
    name: rabb-ribbon
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10002/eureka/
rabb:
  service:
    test: http://RABB-EUREKA-PROVIDER