server:
  port: 20300
spring:
  application:
    name: rabb-sentinel
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
    sentinel:
      transport:
        dashboard: localhost:8880
        port: 8719
      datasource:
        ds:
          nacos:
            server-addr: 127.0.0.1:8848
            data-id: rabb-sentinel-rule.json
            group-id: DEFAULT_GROUP
            username: nacos
            password: nacos
            data-type: json
            rule-type: flow
      eager: true
rabb:
  service:
    provider-service: rabb-nacos-provider
feign:
  sentinel:
    enabled: true