server:
  port: 10001
spring:
  application:
    name: rabb-eureka-consumer
  zipkin:
    base-url: http://localhost:9411/ # 服务端地址
    sender:
      type: web                      # 数据传输方式，web 表示以 HTTP 报文的形式向服务端发送数据
  sleuth:
    sampler:
      probability: 1.0               # 收集数据百分比，默认 0.1（10%）
eureka:
  client:
    service-url:
#      defaultZone: http://127.0.0.1:10003/eureka,http://127.0.0.1:10004/eureka
      defaultZone: http://localhost:10002/eureka
  instance:
    instance-id: consumer-10001
