server:
  port: 10005
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10003/eureka,http://127.0.0.1:10004/eureka
#      defaultZone: http://localhost:10002/eureka
  instance:
    instance-id: provider-10005
spring:
  application:
    name: rabb-eureka-provider
