server:
  port: 10000
eureka:
  client:
    service-url:
      defaultZone: http://lazyrabbit:123456@127.0.0.1:10003/eureka,http://lazyrabbit:123456@127.0.0.1:10004/eureka
#      defaultZone: http://localhost:10002/eureka
  instance:
    instance-id: provider-10000
spring:
  application:
    name: rabb-eureka-provider
