server:
  port: 20501
spring:
  application:
    name: rabb-seata-order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/seata_order?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
rabb:
  service:
    storage-service: rabb-seata-storage-service
mybatis-plus:
  # xml文件位置
  mapper-locations:
    - classpath:mapper/*.xml
  # 实体类位置
  type-aliases-package: xyz.lazyrabbit.seata.order.entity
  # 打印sql日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl